#
# - This uses the latest Docker image, but you might want to use the exact
#   version to avoid any broken pipelines.
#   All available Hugo versions are listed under:
#   https://gitlab.com/pages/hugo/container_registry.
# - Read about the difference between hugo and hugo_extended
#   https://gitlab.com/pages/hugo/-/blob/main/README.md#hugo-vs-hugo_extended.
# - To change the theme, see
#   https://gitlab.com/pages/hugo/-/blob/main/README.md#use-a-custom-theme.
#

image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4

default:
  before_script:
    - apk add --update --no-cache git go
    - git submodule update --init --recursive

pages:
  script:
  - ls -R
  - hugo
  - ls -R
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
