baseURL = "https://fa.babaei.net/"
languageCode = "fa-ir"
title = "محمد صادق بابائی"

theme = "beautifulhugo"
#uglyurls = "true"
Paginate = 8
PaginatePath = "/blog/page"

enableEmoji = true

[permalinks]
    post = "/blog/:slug/"

[Params]
    comments = true
    commit = "https://github.com/NuLL3rr0r/babaei-net-blog-source/tree/"
    dateFormat = "January 2, 2006"
    favicon = "/favicon.ico"
#    gcse = ""
    homeTitle = "محمد صادق بابائی"
    logo = "/img/mohammad-s-babaei.png"
    readingTime = true
    rss = true
    share_img = ""
    socialShare = true
    subtitle = "برنامه نویس C++ / Unreal Engine"
    useChroma = true
    useHLJS = false

[Params.piwik]
    server = "analytics.babaei.net"
    id = "1"

[Author]
    name = "محمد صادق بابائی"
    website = "https://www.babaei.net/"
#    email = "youremail@domain.com"
#    facebook = "username"
#    googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
    github = "NuLL3rr0r"
    gitlab = "NuLL3rr0r"
    twitter = "NuLL3rr0r"
#    reddit = "username"
#    linkedin = "username"
#    xing = "username"
#    stackoverflow = "users/XXXXXXX/username"
#    snapchat = "username"
#    instagram = "username"
#    youtube = "user/username" # or channel/channelname
#    soundcloud = "username"
#    spotify = "username"
#    bandcamp = "username"
#    itchio = "username"
#    vk = "username"
#    paypal = "username"
    telegram = "babaei_net"

[[menu.main]]
    name = "وبلاگ"
    url = ""
    weight = 1

[[menu.main]]
    name = "آرشیو"
    url = "/blog/archives/"
    weight = 2

[[menu.main]]
    name = "رزومه"
    url = "/resume/"
    weight = 3

[[menu.main]]
    name = "پروژه ها"
    url = "/projects/"
    weight = 4

[[menu.main]]
    name = "درباره"
    url = "/about/"
    weight = 5

[[menu.main]]
    identifier = "subscribe"
    name = "اشتراک"
    weight = 6

[[menu.main]]
    parent = "subscribe"
    name = "ایمیل"
    url = "http://subscribe.babaei.net/?lang=fa&subscription=en"
    weight = 1

[[menu.main]]
    parent = "subscribe"
    name = "فید"
    url = "/index.xml"
    weight = 2

[[menu.main]]
    parent = "subscribe"
    name = "تلگرام"
    url = "https://telegram.me/babaei_net"
    weight = 3

[[menu.main]]
    name = "تماس"
    url = "http://subscribe.babaei.net/?lang=fa&contact-form"
    weight = 7

[[menu.main]]
    name = "جستجو"
    url = "/search/"
    weight = 8

[[menu.main]]
    name = "English Blog"
    url = "https://www.babaei.net/"
    weight = 9

[related]
    threshold = 100
    includeNewer = true
    toLower = true

[[related.indices]]
    name = "keywords"
    weight = 150

[[related.indices]]
    name  = "author"
    toLower = true
    weight = 30

[[related.indices]]
    name  = "tags"
    weight = 100

[[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2006"
