baseURL = "https://www.babaei.net/"
languageCode = "en-us"
title = "Mohammad S. Babaei"

theme = "beautifulhugo"
#uglyurls = "true"
Paginate = 8
PaginatePath = "/blog/page"

[permalinks]
    post = "/blog/:slug/"

[Params]
    comments = true
    commit = "https://github.com/NuLL3rr0r/babaei-net-blog-source/tree/"
    dateFormat = "January 2, 2006"
    favicon = "/favicon.ico"
#    gcse = ""
    homeTitle = "Mohammad S. Babaei"
    logo = "/img/mohammad-s-babaei.png"
    readingTime = true
    rss = true
    share_img = ""
    showRelatedPosts = true
    socialShare = true
    subtitle = "C++ / Unreal Engine Developer"
    useChroma = true
    useHLJS = false

[Params.piwik]
    server = "analytics.babaei.net"
    id = "1"

[Author]
    name = "Mohammad S. Babaei"
    website = "https://www.babaei.net/"
#    email = "youremail@domain.com"
#    facebook = "username"
#    googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
    github = "NuLL3rr0r"
    gitlab = "NuLL3rr0r"
    twitter = "NuLL3rr0r"
#    reddit = "username"
#    linkedin = "username"
#    xing = "username"
#    stackoverflow = "users/XXXXXXX/username"
#    snapchat = "username"
#    instagram = "username"
#    youtube = "user/username" # or channel/channelname
#    soundcloud = "username"
#    spotify = "username"
#    bandcamp = "username"
#    itchio = "username"
#    vk = "username"
#    paypal = "username"
    telegram = "babaei_net"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Archives"
    url = "/blog/archives/"
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[[menu.main]]
    identifier = "subscribe"
    name = "Subscribe"
    weight = 6

[[menu.main]]
    parent = "subscribe"
    name = "Subscribe via Email"
    url = "http://subscribe.babaei.net/?lang=en&subscription=en"
    weight = 1

[[menu.main]]
    parent = "subscribe"
    name = "Subscribe via RSS"
    url = "/index.xml"
    weight = 2

[[menu.main]]
    parent = "subscribe"
    name = "Subscribe via Telegram"
    url = "https://telegram.me/babaei_net"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "http://subscribe.babaei.net/?lang=en&contact-form"
    weight = 7

[[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 8

[[menu.main]]
    name = "وبلاگ فارسی"
    url = "https://fa.babaei.net/"
    weight = 9

[related]
    threshold = 100
    includeNewer = true
    toLower = true

[[related.indices]]
    name = "keywords"
    weight = 150

[[related.indices]]
    name  = "author"
    toLower = true
    weight = 30

[[related.indices]]
    name  = "tags"
    weight = 100

[[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2006"

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = true
        respectDoNotTrack = true
        useSessionStorage = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = true
        enableDNT = true
        simple = true
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = true
        privacyEnhanced = true

[services]
    [services.instagram]
        disableInlineCSS = true
    [services.twitter]
        disableInlineCSS = true
