base_url = "https://www.babaei.net"
title = "NuLL3rr0r; The blog of Mohammad S. Babaei"
description = "The hackers way to say 3rr0r"
language_code = "en"

compile_sass = true
highlight_code = true
highlight_theme = "gruvbox-dark"
#theme = ""

generate_tags_pages = true
generate_categories_pages = true

generate_rss = true
rss_limit = 16

[extra]
