base_url = "https://www.babaei.net"
title = "Mohammad S. Babaei"
description = "The blog of Mohammad S. Babaei"
language_code = "en"

compile_sass = true
highlight_code = true
highlight_theme = "gruvbox-dark"
theme = "minimal-blog"

generate_tags_pages = false
generate_categories_pages = false

generate_rss = true
rss_limit = 16

[extra]
minimal_blog_author = "Mohammad S. Babaei"
minimal_blog_avatar = "images/mohammad-s-babaei.png"
minimal_blog_avatar_thumbnail = "images/mohammad-s-babaei_thumbnail.png"
minimal_blog_excerpt_link = "Read more..."
minimal_blog_rtl = false
