baseURL = "https://www.babaei.net/"
languageCode = "en-us"
title = "Mohammad S. Babaei"

theme = "beautifulhugo"
#uglyurls = "true"
Paginate = 8
PaginatePath = "/blog/page"

[permalinks]
    post = "/blog/:slug/"

[Params]
    comments = true
    commit = "https://github.com/NuLL3rr0r/babaei-net-blog-source/tree/"
    dateFormat = "January 2, 2006"
    favicon = ""
#    gcse = ""
    logo = "img/mohammad-s-babaei.png"
    piwik = ""
    readingTime = true
    rss = true
    share_img = ""
    subtitle = "Unreal Engine / C++ Developer"
    useChroma = true

[Author]
    name = "Mohammad S. Babaei"
    website = "https://www.babaei.net/"
#    email = "youremail@domain.com"
#    facebook = "username"
#    googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
    github = "NuLL3rr0r"
    gitlab = "NuLL3rr0r"
    twitter = "NuLL3rr0r"
#    reddit = "username"
#    linkedin = "username"
#    xing = "username"
#    stackoverflow = "users/XXXXXXX/username"
#    snapchat = "username"
#    instagram = "username"
#    youtube = "user/username" # or channel/channelname
#    soundcloud = "username"
#    spotify = "username"
#    bandcamp = "username"
#    itchio = "username"
#    vk = "username"
#    paypal = "username"
    telegram = "babaei_net"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Archives"
    url = "/blog/archives/"
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[[menu.main]]
    identifier = "subscribe"
    name = "Subscribe"
    weight = 6

[[menu.main]]
    parent = "subscribe"
    name = "Subscribe via Email"
    url = "http://subscribe.babaei.net/?lang=en&subscription=en"
    weight = 1

[[menu.main]]
    parent = "subscribe"
    name = "Subscribe via RSS"
    url = "/index.xml"
    weight = 2

[[menu.main]]
    parent = "subscribe"
    name = "Subscribe via Telegram"
    url = "https://telegram.me/babaei_net"
    weight = 3

[[menu.main]]
    name = "Email"
    url = "http://subscribe.babaei.net/?lang=en&contact-form"
    weight = 7

[[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 8

[[menu.main]]
    name = "وبلاگ فارسی"
    url = "https://fa.babaei.net/"
    weight = 9
