# config
cover_high: /img/cover_high.jpg
cover_medium: /img/cover_medium.jpg
cover_low: /img/cover_low.jpg
logo: /img/logo.png
top_saying:
- title: 
- content: 
bottom_saying:
# Content
excerpt_link: Read on

rss: /atom.xml

highlightjs: vs

# Miscellaneous
github: https://github.com/NuLL3rr0r
twitter: https://twitter.com/NuLL3rr0r

#Links
links:
- name: وبلاگ فارسی
  link: http://fa.babaei.net/

# Search
simple_search: https://www.duckduckgo.com/
simple_search_site: babaei.net
simple_search_site_key: sites
simple_search_query_key: q
simple_search_placeholder: Search&hellip;

# Sharing
twitter_user: NuLL3rr0r

# Google Analytics
google_analytics_tracking_id: UA-2377757-1
google_analytics_set_domain_name: babaei.net  # Tracking one domain with multiple subdomains
google_analytics_set_allow_linker: false      # Tracking multiple top-level domains

# Piwik
piwik_enable: true

